<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/add_removed_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# appending a value at the end of the array using append function
import numpy as np
a = np.array([1, 2, 3])
b=np.append(a,4)
print("appending a value at the end of the array", b)
a1 = np.array([[1, 2, 3], [7, 8, 9]])
c=np.append(a1,4)
print("appending a value to the 2-D array", c)
# appending two arrays with axis=None
a = np.array([[1, 2, 3], [7, 8, 9]])
b = np.array([[11, 21, 31], [42, 52, 62]])
print("The first array:\n",a)
print("The second array:\n",b)
c = np.append(a,b)
print("The resultant array after appending a & b:", c)
# With axis=0
c1=np.append(a,b,axis=0)
print("The resultant array after appending a & b along row:", c1)
# With axis=1
c2=np.append(a,b,axis=1)
print("The resultant array after appending a & b along column:", c2)


appending a value at the end of the array [1 2 3 4]
appending a value to the 2-D array [1 2 3 7 8 9 4]
The first array:
 [[1 2 3]
 [7 8 9]]
The second array:
 [[11 21 31]
 [42 52 62]]
The resultant array after appending a & b: [ 1  2  3  7  8  9 11 21 31 42 52 62]
The resultant array after appending a & b along row: [[ 1  2  3]
 [ 7  8  9]
 [11 21 31]
 [42 52 62]]
The resultant array after appending a & b along column: [[ 1  2  3 11 21 31]
 [ 7  8  9 42 52 62]]
