<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
# operations on single array
a = np.array([1, 2, 5, 3])
print ("Adding 1 to every element:", a+1) # add 1 to every element
print ("Subtracting 3 from each element:", a-3) # subtract 3 from eachelement
print ("Multiplying each element by 10:", a*10) # multiply each element by 10
print ("Squaring each element:", a**2) # square each element
a *= 2 # modify existing array
print ("Doubled each element of original array:", a)
# Arithmetic operations
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2=np.array([[4., 5., 7.], [3., 6., 9.]])
# Addition of arrays
s_arr= arr1+arr2
s_arr1=np.add(arr1,arr2)
print ("Addition of two arrays:", s_arr)
print ("Addition of two arrays using add function:", s_arr1)
# subtraction of arrays
su_arr=arr1-arr2
su_arr1=np.subtract(arr1,arr2)
print ("Subtraction of two arrays:", su_arr)
print ("Subtraction of two arrays using subtract function:", su_arr)
# Element-wise multiplication
m_arr=arr1*arr2
print ("Element-wise multiplication of two arrays:", m_arr)
# Matrix multiplication
arr1 = np.array([[1., 2.], [4., 5.]])
arr2=np.array([[4., 5.], [3., 6.]])
m_arr1=np.dot(arr1, arr2)
m_arr2=np.matmul(arr1, arr2)
m_arr3=arr1@arr2
print ("Matrix multiplication using dot:", m_arr1)
print ("Matrix multiplication using matmul:", m_arr2)
print ("Matrix multiplication using @ symbol:", m_arr3)
# Element-wise Division
d_arr=arr1/arr2
d_arr1=np.divide(arr1,arr2)
print ("Division of arrays:", d_arr)
print ("Division of arrays using divide function:", d_arr)




Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]
Addition of two arrays: [[ 5.  7. 10.]
 [ 7. 11. 15.]]
Addition of two arrays using add function: [[ 5.  7. 10.]
 [ 7. 11. 15.]]
Subtraction of two arrays: [[-3. -3. -4.]
 [ 1. -1. -3.]]
Subtraction of two arrays using subtract function: [[-3. -3. -4.]
 [ 1. -1. -3.]]
Element-wise multiplication of two arrays: [[ 4. 10. 21.]
 [12. 30. 54.]]
Matrix multiplication using dot: [[10. 17.]
 [31. 50.]]
Matrix multiplication using matmul: [[10. 17.]
 [31. 50.]]
Matrix multiplication using @ symbol: [[10. 17.]
 [31. 50.]]
Division of arrays: [[0.25       0.4       ]
 [1.33333333 0.83333333]]
Division of arrays using divide function: [[0.25       0.4       ]
 [1.33333333 0.83333333]]
