<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/creationtechniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
c=np.zeros((3,4))
print("\nAn array intialized with all zeros:",c)
d=np.ones((3,4))
print("An array intialized with all ones:",d)
e=np.random.random((2,2))
print("A random array:",e)
f=np.arange(0,30,5)
print("\n A sequential array with steps of 5:",f)
g=np.linspace(0,5,10)
print("\n A sequential array with 10 values between 0 and 5 :",g)
h=np.full((3,3),8)
print("\n A array with all values being 8:",h)



An array intialized with all zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array intialized with all ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
A random array: [[0.53074373 0.12648899]
 [0.33222564 0.7525701 ]]

 A sequential array with steps of 5: [ 0  5 10 15 20 25]

 A sequential array with 10 values between 0 and 5 : [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

 A array with all values being 8: [[8 8 8]
 [8 8 8]
 [8 8 8]]
