<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/positionarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Deleting the values at particular positions in the array
#Working on 1D
import numpy as np
arr = np.array([5,6,7,8,1,2])
print("arr : \n", arr)
print("Shape : ", arr.shape)
# deletion from 1D array
object = 2
a = np.delete(arr, object)
print("\ndeleteing {} from array : \n {}".format(object,a))
print("Shape : ", a.shape)

object = [1, 3]
b = np.delete(arr, object)
#print("\ndeleteing {} from array : \n {}".format(object,a))
#print("Shape : ", a.shape)
print("\n",b)
print("\n",b.shape)
arr = np.arange(12).reshape(3, 4)
print("arr : \n", arr)
print("Shape : ", arr.shape)
# deletion from 2D array
a = np.delete(arr, 1, 0)
print("\ndeleteing arr 2 times : \n", a)
print("Shape : ", a.shape)
# deletion from 2D array
a = np.delete(arr, 1, 1)
print("\ndeleteing arr 2 times : \n", a)
print("Shape : ", a.shape)


arr : 
 [5 6 7 8 1 2]
Shape :  (6,)

deleteing 2 from array : 
 [5 6 8 1 2]
Shape :  (5,)

 [5 7 1 2]

 (4,)
arr : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (3, 4)

deleteing arr 2 times : 
 [[ 0  1  2  3]
 [ 8  9 10 11]]
Shape :  (2, 4)

deleteing arr 2 times : 
 [[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
Shape :  (3, 3)
