<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/praticualindex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# inserting a value at particular index in the array
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
print("Axis parameter not passed. The input array is flattened beforeinsertion.")
print(np.insert(a,3,[11,12]))
print("Axis parameter passed. The values array is broadcast to match inputarray.")
print('Broadcast along axis 0:')
print(np.insert(a,1,[11],axis = 0))
print('Broadcast along axis 1:')
print(np.insert(a,1,[11],axis = 1))
# inserting a value at different positions
arr = np.arange(12).reshape(3, 4)
print('\n',arr)
a = np.insert(arr, (2, 4), 9)
print('\n',a)
# inserting and broadcasting at different positions in the array
b = np.insert(arr, (0, 3), 66, axis = 1)
print('\n',b)

Axis parameter not passed. The input array is flattened beforeinsertion.
[ 1  2  3 11 12  4  5  6]
Axis parameter passed. The values array is broadcast to match inputarray.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [ 0  1  9  2  3  9  4  5  6  7  8  9 10 11]

 [[66  0  1  2 66  3]
 [66  4  5  6 66  7]
 [66  8  9 10 66 11]]
