<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6])
# reshape an 1-D array into 2-D array
print("reshaping the array into an array of size (3,2)\n",a.reshape(3,2))
print("reshaping the array into an array of size (2,3)\n",a.reshape(2,3))
print("reshaping the array into an array of size (6,1)\n",a.reshape(6,1))
# reshape an array into 3 dimensional matrix
a1=np.arange(0,9)
print("reshaping the array into an array of size (3,2)",a1.reshape(3, 1, 3))
# resizing the array into a larger with repeated copies of the original array
a2=np.array([[0,1],[2,3]])
print(np.resize(a2,(2,3)))
print(np.resize(a2,(1,4)))
print(np.resize(a2,(2,4)))

reshaping the array into an array of size (3,2)
 [[1 2]
 [3 4]
 [5 6]]
reshaping the array into an array of size (2,3)
 [[1 2 3]
 [4 5 6]]
reshaping the array into an array of size (6,1)
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
reshaping the array into an array of size (3,2) [[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
[[0 1 2]
 [3 0 1]]
[[0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]]
