<a href="https://colab.research.google.com/github/Anjigampala/Gampala-Jai-Anjaneya-/blob/main/square%20root.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# other mathematical functions
import numpy as np
# natural logarithm
a=np.array([[1, np.e, np.e**2, 0]])
print("Element -wise logarithm of the array:", np.log(a))
# log base 10
b=np.array([100, 1000, 50, 1e-15])
print("Element-wise logarithm of the array:", np.log10(a))
# log base 2
c=np.array([0, 1, 2, 4, 8, 16,32])
print("Element-wise logarithm of the array:", np.log2(a))
# square root
d=np.array([1, 4, 9, 36, 49, 64, 81, 100])
print("square roots of elements of the array", np.sqrt(d))
# minimum and maximum of the elements in the array
arr = np.array([[1, 5, 6], [4, 7, 2], [3, 1, 9]])
print ("Largest element is:", arr.max()) # maximum element of array
print ("Row-wise maximum elements:", arr.max(axis = 1))
print ("Column-wise minimum elements:", arr.min(axis = 0)) # minimum element of array
# sum of elements in the array
e=np.array([[7, 8, 9, 12, 13, 15, 17],[18, 19, 20, 11, 13, 19, 21]])
print(e)
print(e.sum())
print(e.sum(axis=0)) # summation along row (axis=0)
print(e.sum(axis=1)) # summation along column (axis=1)


Element -wise logarithm of the array: [[  0.   1.   2. -inf]]
Element-wise logarithm of the array: [[0.         0.43429448 0.86858896       -inf]]
Element-wise logarithm of the array: [[0.         1.44269504 2.88539008       -inf]]
square roots of elements of the array [ 1.  2.  3.  6.  7.  8.  9. 10.]
Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
[[ 7  8  9 12 13 15 17]
 [18 19 20 11 13 19 21]]
202
[25 27 29 23 26 34 38]
[ 81 121]


<ipython-input-6-66dcb26675af>:5: RuntimeWarning: divide by zero encountered in log
  print("Element -wise logarithm of the array:", np.log(a))
<ipython-input-6-66dcb26675af>:8: RuntimeWarning: divide by zero encountered in log10
  print("Element-wise logarithm of the array:", np.log10(a))
<ipython-input-6-66dcb26675af>:11: RuntimeWarning: divide by zero encountered in log2
  print("Element-wise logarithm of the array:", np.log2(a))
